export const initialVal = {
    fdcId: 0,
    dataType: "",
    description: "",
    foodCode: "",
    foodNutrients: [{
        nutrientId: 0,
      nutrientName: "",
      nutrientNumber: 0,
      unitName: "",
      derivationCode: "",
      derivationDescription: "",
      derivationId:0,
      value: 0,
      foodNutrientSourceId: 0,
      foodNutrientSourceCode: 0,
      foodNutrientSourceDescription: "",
      rank: 0,
      indentLevel:0,
      foodNutrientId: 0,
      percentDailyValue: 0
      }],
    publicationDate: "",
    scientificName: "",
    brandOwner: "",
    gtinUpc: 0,
    ingredients: "",
    ndbNumber: 0,
    additionalDescriptions: "",
    allHighlightFields: "",
    score: 0
  }

  export const foodNutrients= {
    nutrientId: 0,
  nutrientName: "",
  nutrientNumber: 0,
  unitName: "",
  derivationCode: "",
  derivationDescription: "",
  derivationId:0,
  value: 0,
  foodNutrientSourceId: 0,
  foodNutrientSourceCode: 0,
  foodNutrientSourceDescription: "",
  rank: 0,
  indentLevel:0,
  foodNutrientId: 0,
  percentDailyValue: 0
  }